nps.vn/routes/admin.php
<?php
Route::prefix('madmin')->name('admin.')->middleware('auth')->group(function() {
    Route::get('dashboard', 'Admin\HomeController@index');

    Route::prefix('users')->name('user.')->group(function() {
        Route::get('/', 'Admin\UserController@index')->name('index');
        Route::get('/add', 'Admin\UserController@create')->name('add');
        Route::post('/add', 'Admin\UserController@store');
        Route::get('/show/{id}', 'Admin\UserController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\UserController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\UserController@update');
        Route::get('/delete/{id}', 'Admin\UserController@delete')->name('delete');
    });

    Route::prefix('administrators')->name('admin.')->group(function() {
        Route::get('/', 'Admin\AdminController@index')->name('index');
        Route::get('/add', 'Admin\AdminController@create')->name('add');
        Route::post('/add', 'Admin\AdminController@store');
        Route::get('/show/{id}', 'Admin\AdminController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\AdminController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\AdminController@update');
        Route::get('/delete/{id}', 'Admin\AdminController@delete')->name('delete');
    });

    Route::prefix('category')->name('category.')->group(function() {
        Route::get('/', 'Admin\CategoryController@index')->name('index');
        Route::get('/add', 'Admin\CategoryController@create')->name('add');
        Route::post('/add', 'Admin\CategoryController@store');
        Route::get('/show/{id}', 'Admin\CategoryController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\CategoryController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\CategoryController@update');
        Route::get('/delete/{id}', 'Admin\CategoryController@delete')->name('delete');
    });

    Route::prefix('catalog')->name('catalog.')->group(function() {
        Route::get('/', 'Admin\CatalogController@index')->name('index');
        Route::get('/add', 'Admin\CatalogController@create')->name('add');
        Route::post('/add', 'Admin\CatalogController@store');
        Route::get('/show/{id}', 'Admin\CatalogController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\CatalogController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\CatalogController@update');
        Route::get('/delete/{id}', 'Admin\CatalogController@delete')->name('delete');
    });

    Route::prefix('posts')->name('post.')->group(function() {
        Route::get('/', 'Admin\PostController@index')->name('index');
        Route::get('/add', 'Admin\PostController@create')->name('add');
        Route::post('/add', 'Admin\PostController@store');
        Route::get('/show/{id}', 'Admin\PostController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\PostController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\PostController@update');
        Route::get('/delete/{id}', 'Admin\PostController@delete')->name('delete');
    });

    Route::prefix('hosting')->name('hosting.')->group(function() {
        Route::get('/', 'Admin\HostingController@index')->name('index');
        Route::get('/add', 'Admin\HostingController@create')->name('add');
        Route::post('/add', 'Admin\HostingController@store');
        Route::get('/show/{id}', 'Admin\HostingController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\HostingController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\HostingController@update');
        Route::get('/delete/{id}', 'Admin\HostingController@delete')->name('delete');
    });

    Route::prefix('vps')->name('vps.')->group(function() {
        Route::get('/', 'Admin\VPSController@index')->name('index');
        Route::get('/add', 'Admin\VPSController@create')->name('add');
        Route::post('/add', 'Admin\VPSController@store');
        Route::get('/show/{id}', 'Admin\VPSController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\VPSController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\VPSController@update');
        Route::get('/delete/{id}', 'Admin\VPSController@delete')->name('delete');
    });

    Route::prefix('dedicated')->name('dedicated.')->group(function() {
        Route::get('/', 'Admin\ServerController@index')->name('index');
        Route::get('/add', 'Admin\ServerController@create')->name('add');
        Route::post('/add', 'Admin\ServerController@store');
        Route::get('/show/{id}', 'Admin\ServerController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\ServerController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\ServerController@update');
        Route::get('/delete/{id}', 'Admin\ServerController@delete')->name('delete');
    });

    Route::prefix('rack')->name('rack.')->group(function() {
        Route::get('/', 'Admin\RackController@index')->name('index');
        Route::get('/add', 'Admin\RackController@create')->name('add');
        Route::post('/add', 'Admin\RackController@store');
        Route::get('/show/{id}', 'Admin\RackController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\RackController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\RackController@update');
        Route::get('/delete/{id}', 'Admin\RackController@delete')->name('delete');
    });

    Route::prefix('colocation')->name('colocation.')->group(function() {
        Route::get('/', 'Admin\ColocationController@index')->name('index');
        Route::get('/add', 'Admin\ColocationController@create')->name('add');
        Route::post('/add', 'Admin\ColocationController@store');
        Route::get('/show/{id}', 'Admin\ColocationController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\ColocationController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\ColocationController@update');
        Route::get('/delete/{id}', 'Admin\ColocationController@delete')->name('delete');
    });

    Route::prefix('nwall')->name('nwall.')->group(function() {
        Route::get('/', 'Admin\NWallController@index')->name('index');
        Route::get('/add', 'Admin\NWallController@create')->name('add');
        Route::post('/add', 'Admin\NWallController@store');
        Route::get('/show/{id}', 'Admin\NWallController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\NWallController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\NWallController@update');
        Route::get('/delete/{id}', 'Admin\NWallController@delete')->name('delete');
    });

    Route::prefix('seo')->name('seo.')->group(function() {
        Route::get('/', 'Admin\SeoController@index')->name('index');
        Route::get('/add', 'Admin\SeoController@create')->name('add');
        Route::post('/add', 'Admin\SeoController@store');
        Route::get('/show/{id}', 'Admin\SeoController@show');
        Route::get('/edit/{id}', 'Admin\SeoController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\SeoController@update');
        Route::get('/delete/{id}', 'Admin\SeoController@delete')->name('delete');
    });

    Route::prefix('pages')->name('pages.')->group(function() {
        Route::get('/', 'Admin\PageController@index')->name('index');
        Route::get('/add', 'Admin\PageController@create')->name('add');
        Route::post('/add', 'Admin\PageController@store');
        Route::get('/show/{id}', 'Admin\PageController@show');
        Route::get('/edit/{id}', 'Admin\PageController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\PageController@update');
        Route::get('/delete/{id}', 'Admin\PageController@delete')->name('delete');
    });

    Route::prefix('config')->name('config.')->group(function() {
        Route::get('/', 'Admin\ConfigController@index');
        Route::get('/homepage', 'Admin\ConfigController@show_homepage')->name('show_homepage');
        Route::get('/homepage/{id}', 'Admin\ConfigController@edit_homepage')->name('edit_homepage');
        Route::post('/homepage/{id}', 'Admin\ConfigController@update_homepage');
    });
});

nps.vn/routes/web.php
<?php
use App\Http\Controllers\Helper\MAC;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth::routes();

Route::get('/mlogin', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/mlogin', 'Auth\LoginController@login');
// Route::get('/mregister', 'Auth\RegisterController@showRegistrationForm')->name('register');
// Route::post('/mregister/', 'Auth\RegisterController@register');
// Route::get('/mpassword/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
// Route::post('/mpassword/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
// Route::get('/mpassword/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
// Route::post('/mpassword/reset', 'Auth\ResetPasswordController@reset');
Route::get('/logout', 'AuthController@logout')->name('logout');

include base_path('routes/admin.php');
// include base_path('routes/view.php');



Route::get('/', 'Website\HomeController@index')->name('home');
Route::get('su-kien/du-doan-ty-so-viet-nam-malaysia.html', 'Website\HomeController@event');
Route::get('su-kien/du-doan-ket-qua-viet-nam-malaysia.html', 'Website\HomeController@bongda');
Route::get('su-kien/du-doan-ket-qua-viet-nam-indo.html', 'Website\HomeController@vnindo');
// Route::get('/hosting.html', 'Website\HomeController@hosting');
// Route::get('/vps.html', 'Website\HomeController@hosting');
// Route::get('/dedicated.html', 'Website\HomeController@hosting');
// Route::get('/tu-rack.html', 'Website\HomeController@hosting');
Route::get('/2019/04/17/anti-ddos-la-gi', function() {
    return redirect('https://www.nps.vn/kb/blogs/kien-thuc/anti-ddos/dos-ddos-la-gi-cach-chong-hacker-ddos-nhu-the-nao.html');
});

Route::get('/{slug}.html', 'Website\HomeController@page');
// Route::get('/sitemapnps.xml', 'Website\HomeController@xml');
// $segment = '';
// $page = Request::segment(1);
// if (!empty($page)) {
// 	$segment = MAC::redirect_page($page);

// 	if ($segment->status == 200) {
// 		dd($page);
// 		Route::get('/'.$page, 'Website\HomeController@page')->name('page');
// 	}else{
// 		Route::get('/404');
// 	}
// }else{
// 	Route::get('/404');
// }

nps.vn/resources/views/admin/admin/add.blade.php
@extends('admin.home')
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-header">
					<div class="row">
						<div class="col-md-12 card_title">
							<h4>Thêm mới quản trị viên</h4>
						</div>
					</div>
				</div>
				@include('admin.notify')
				<div class="card-body">
					<form action="" method="post" accept-charset="utf-8">
						@csrf
						<div class="form-group row">
							<div class="col-md-6 pl-0 form_mac">
								<label class="label_mac">Username</label>
								<input type="text" name="username" class="form-control input_mac" value="{{ old('username') }}" maxlength="50" required="">
							</div>
							<div class="col-md-6 pr-0 form_mac">
								<label class="label_mac">Email</label>
								<input type="email" name="email" class="form-control input_mac" value="{{ old('email') }}" maxlength="50" required="">
							</div>
						</div>
						<div class="form-group row">
							<div class="col-md-6 pl-0 form_mac">
								<label class="label_mac">Mật khẩu</label>
								<input type="password" name="password" class="form-control input_mac" value="" minlength="8" maxlength="16" required="">
							</div>
							<div class="col-md-6 pr-0 form_mac">
								<label class="label_mac">Nhập lại mật khẩu</label>
								<input type="password" name="password_confirmation" class="form-control input_mac" value="" minlength="8" maxlength="16" required="">
							</div>
						</div>
						<div class="form-group row">
							<div class="col-md-6 pl-0 form_mac">
								<label class="label_mac">Họ và tên</label>
								<input type="text" name="fullname" class="form-control input_mac" value="{{ old('fullname') }}" maxlength="200" required="">
							</div>
							<div class="col-md-6 pr-0 form_mac">
								<label class="label_mac">Số điện thoại</label>
								<input type="number" step="any" name="phone" class="form-control input_mac" value="{{ old('phone') }}" maxlength="12" required="">
							</div>
						</div>
						<div class="form-group row">
							<div class="col-md-6 pl-0 form_mac">
								<label class="label_mac">Địa chỉ</label>
								<input type="text" name="address" class=" form-control input_mac" value="{{ old('address') }}" maxlength="200">
							</div>
							<div class="col-md-6 pr-0 form_mac">
								<select name="role" class="form-control select_mac">
									<option value="">-- Select permission --</option>}
									@foreach (config('role') as $key => $value)
										@if ($key != 'user')
											<option value="{{ $key }}" class="option_mac">{{ $value }}</option>
										@endif
									@endforeach
								</select>
							</div>
						</div>
						<div class="form-group row">
							<div class="col-md-4 pl-0 form_mac">
								<label class="label_mac">Công ty</label>
								<input type="text" name="company" class="form-control input_mac" value="{{ old('company') }}" maxlength="200">
							</div>
							<div class="col-md-4 form_mac">
								<label class="label_mac">Thành phố</label>
								<input type="text" name="city" class="form-control input_mac" value="{{ old('city') }}" maxlength="200">
							</div>
							<div class="col-md-4 pr-0 form_mac">
								<label class="label_mac">Quốc gia</label>
								<input type="text" name="country" class="form-control input_mac" value="{{ old('country') }}" maxlength="200">
							</div>
						</div>
						<div class="form-group row">
							<div class="col-md-12 px-0 form_mac">
								<label class="label_mac">Description</label>
								<textarea name="description" class="form-control input_mac" rows="1" maxlength="2000">{{ old('description') }}</textarea>
							</div>
						</div>
						<div class="form-group text-right">
							<button type="submit" class="btn">Thêm mới</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

nps.vn/resources/views/admin/admin/edit.blade.php
@extends('admin.home')
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-header">
					<div class="row">
						<div class="col-md-12 card_title">
							<h4>Cập nhật thông tin quản trị viên</h4>
						</div>
					</div>
				</div>
				@include('admin.notify')
				<div class="card-body">
					<form action="" method="post" accept-charset="utf-8">
						@csrf
						<div class="form-group row">
							<div class="col-md-6 pl-0 form_mac">
								<label class="label_mac">Username</label>
								<input type="text" name="username" class="form-control input_mac" value="{{ $user->name }}" maxlength="50">
							</div>
							<div class="col-md-6 pr-0 form_mac">
								<label class="label_mac">Email</label>
								<input type="email" name="email" class="form-control input_mac" value="{{ $user->email }}" maxlength="50" required="">
							</div>
						</div>
						<div class="form-group row">
							<div class="col-md-6 pl-0 form_mac">
								<label class="label_mac">Họ và tên</label>
								<input type="text" name="fullname" class="form-control input_mac" value="{{ $user->fullname }}" maxlength="200" required="">
							</div>
							<div class="col-md-6 pr-0 form_mac">
								<label class="label_mac">Số điện thoại</label>
								<input type="number" step="any" name="phone" class="form-control input_mac" value="{{ $user->phone }}" maxlength="12" required="">
							</div>
						</div>
						<div class="form-group row">
							<div class="col-md-6 pl-0 form_mac">
								<select name="role" class="form-control select_mac">
									<option value="">-- Select permission --</option>}
									@foreach (config('role') as $key => $value)
										@if ($key != 'user')
										<option value="{{ $key }}" class="option_mac" {{ in_array($key, json_decode($user->roles)) ? 'selected' : '' }}>{{ $value }}</option>
										@endif
									@endforeach
								</select>
							</div>
							<div class="col-md-6 pr-0 form_mac">
								<select name="status" class="form-control select_mac">
									@foreach (config('user_status') as $item)
									<option value="{{ $item }}" {{ ($item == $user->status) ? 'selected' : '' }}>{{ $item }}</option>
									@endforeach
								</select>
							</div>
						</div>
						<div class="form-group row">
							<div class="col-md-12 pl-0 form_mac">
								<label class="label_mac">Địa chỉ</label>
								<input type="text" name="address" class=" form-control input_mac" value="{{ $user->address }}" maxlength="200">
							</div>
						</div>
						<div class="form-group row">
							<div class="col-md-4 pl-0 form_mac">
								<label class="label_mac">Công ty</label>
								<input type="text" name="company" class="form-control input_mac" value="{{ $user->company }}" maxlength="200">
							</div>
							<div class="col-md-4 form_mac">
								<label class="label_mac">Thành phố</label>
								<input type="text" name="city" class="form-control input_mac" value="{{ $user->city }}" maxlength="200">
							</div>
							<div class="col-md-4 pr-0 form_mac">
								<label class="label_mac">Quốc gia</label>
								<input type="text" name="country" class="form-control input_mac" value="{{ $user->country }}" maxlength="200">
							</div>
						</div>
						<div class="form-group row">
							<div class="col-md-12 px-0 form_mac">
								<label class="label_mac">Description</label>
								<textarea name="description" class="form-control input_mac" rows="1" maxlength="2000">{{ $user->description }}</textarea>
							</div>
						</div>
						<div class="form-group row password_form">
							<div class="col-md-6 pl-0 form_mac">
								<label class="label_mac">Mật khẩu</label>
								<input type="password" name="password" class="form-control input_mac" value="" >
							</div>
							<div class="col-md-6 pr-0 form_mac">
								<label class="label_mac">Nhập lại mật khẩu</label>
								<input type="password" name="password_confirmation" class="form-control input_mac" value="">
							</div>
						</div>
						<div class="form-group row">
							<div class="col-md-6 pl-0">
								<button type="button" class="btn btn-secondary change_pass_btn">Thay đổi mật khẩu</button>
								<input type="checkbox" name="change_pass" class="change_pass d-none" value="0" >
							</div>
							<div class="col-md-6 pr-0 text-right">
								<button type="submit" class="btn">Cập nhật thông tin</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$('.change_pass_btn').click(function() {
			if ($('.change_pass').is(':checked')) {
				$('.change_pass').prop('checked', false);
				$('.change_pass').val(0);
				$('.change_pass_btn').html('Thay đổi mật khẩu');
				$('.password_form').css({'display':'none'});
				$('[name = "password"]').removeAttr('minlength maxlength required');
				$('[name = "password_confirmation"]').removeAttr('minlength maxlength required');
			}else{
				$('.change_pass').prop('checked', true);
				$('.change_pass').val(1);
				$('.change_pass_btn').html('Bỏ qua');
				$('.password_form').css({'display':'flex'});
				$('[name = "password"]').attr({minlength:'8', maxlength:'16', required:''});
				$('[name = "password_confirmation"]').attr({minlength:'8', maxlength:'16', required:''});
			}
		});

</script>
@endsection

nps.vn/resources/views/admin/admin/index.blade.php
@extends('admin.home')
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-header">
					<div class="row">
						<div class="col-md-4 card_title">
							<h4>Danh sách quản trị viên</h4>
						</div>
						<div class="col-md-4 text-center btn_add">
							<a href="{{ route('admin.admin.add') }}"><i class="fas fa-plus"></i></a>
						</div>
						<div class="col-md-4 card_search">
							<form action="" method="post" accept-charset="utf-8" class="">
								@csrf
								<div class="input-group justify-content-end">
									<input type="text" class="form-control input_search" name="" value="" placeholder="Search">
									<button type="submit" class="btn btn-white"><i class="fas fa-search"></i></button>
								</div>
							</form>
						</div>
					</div>
				</div>
				@include('admin.notify')
				<div class="card-body">
					<div class="table-responsive">
						<table class="table table-hover table-striped">
							<thead>
								<tr>
									<th>ID</th>
									<th>Name</th>
									<th>Email</th>
									<th>Permission</th>
									<th>Created Date</th>
									<th>Login Time</th>
									<th></th>
								</tr>
							</thead>
							<tbody>
								@foreach (@$list as $item)
								<tr>
									<td>{{ @$item->id }}</td>
									<td><a href="{{ route('admin.admin.edit', ['id' => $item->id]) }}" class="px-0">{{ @$item->name }}</a></td>
									<td><a href="{{ route('admin.admin.edit', ['id' => $item->id]) }}" class="px-0">{{ @$item->email }}</a></td>
									<td>{{ implode(' | ', json_decode(@$item->roles)) }}</td>
									<td>{{ @$item->created_at }}</td>
									<td>{{ @$item->last_login }}</td>
									<td>
										<a href="{{ route('admin.admin.edit', ['id' => $item->id]) }}"><i class="fas fa-edit"></i></a>
										<a href="{{ route('admin.admin.delete', ['id' => $item->id]) }}" onclick="return confirm('Bạn có chắn chắn muốn xóa quản trị viên này không?');"><i class="fas fa-trash-alt"></i></a>
									</td>
								</tr>
								@endforeach
							</tbody>
						</table>
						{{ $list->links() }}
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	var formMac0 =  Array.from(document.querySelectorAll('.form_mac'));
		formMac0.forEach(function(el){
			if(Array.from(el.children)[1] != undefined){
				el.classList.add('form-mac-input');
			}
		})

	var formMac =Array.from(document.querySelectorAll('.form_mac.form-mac-input'));
		formMac.forEach(function(el){
		var labelMac = el.querySelector('.label_mac'),
			inputMac = el.querySelector('.input_mac')
		if(inputMac.value != ""){
			labelMac.style.transition = "all .3s ease";
			labelMac.style.top = "-20px";
		}
		inputMac.addEventListener('click', function(){
			labelMac.style.transition = "all .3s ease";
			labelMac.style.top = "-20px";
		})
	})
</script>
@endsection