nps.vn/routes/admin.php
<?php
Route::prefix('madmin')->name('admin.')->middleware('auth')->group(function() {
    Route::get('dashboard', 'Admin\HomeController@index');

    Route::prefix('users')->name('user.')->group(function() {
        Route::get('/', 'Admin\UserController@index')->name('index');
        Route::get('/add', 'Admin\UserController@create')->name('add');
        Route::post('/add', 'Admin\UserController@store');
        Route::get('/show/{id}', 'Admin\UserController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\UserController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\UserController@update');
        Route::get('/delete/{id}', 'Admin\UserController@delete')->name('delete');
    });

    Route::prefix('administrators')->name('admin.')->group(function() {
        Route::get('/', 'Admin\AdminController@index')->name('index');
        Route::get('/add', 'Admin\AdminController@create')->name('add');
        Route::post('/add', 'Admin\AdminController@store');
        Route::get('/show/{id}', 'Admin\AdminController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\AdminController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\AdminController@update');
        Route::get('/delete/{id}', 'Admin\AdminController@delete')->name('delete');
    });

    Route::prefix('category')->name('category.')->group(function() {
        Route::get('/', 'Admin\CategoryController@index')->name('index');
        Route::get('/add', 'Admin\CategoryController@create')->name('add');
        Route::post('/add', 'Admin\CategoryController@store');
        Route::get('/show/{id}', 'Admin\CategoryController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\CategoryController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\CategoryController@update');
        Route::get('/delete/{id}', 'Admin\CategoryController@delete')->name('delete');
    });

    Route::prefix('catalog')->name('catalog.')->group(function() {
        Route::get('/', 'Admin\CatalogController@index')->name('index');
        Route::get('/add', 'Admin\CatalogController@create')->name('add');
        Route::post('/add', 'Admin\CatalogController@store');
        Route::get('/show/{id}', 'Admin\CatalogController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\CatalogController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\CatalogController@update');
        Route::get('/delete/{id}', 'Admin\CatalogController@delete')->name('delete');
    });

    Route::prefix('posts')->name('post.')->group(function() {
        Route::get('/', 'Admin\PostController@index')->name('index');
        Route::get('/add', 'Admin\PostController@create')->name('add');
        Route::post('/add', 'Admin\PostController@store');
        Route::get('/show/{id}', 'Admin\PostController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\PostController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\PostController@update');
        Route::get('/delete/{id}', 'Admin\PostController@delete')->name('delete');
    });

    Route::prefix('hosting')->name('hosting.')->group(function() {
        Route::get('/', 'Admin\HostingController@index')->name('index');
        Route::get('/add', 'Admin\HostingController@create')->name('add');
        Route::post('/add', 'Admin\HostingController@store');
        Route::get('/show/{id}', 'Admin\HostingController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\HostingController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\HostingController@update');
        Route::get('/delete/{id}', 'Admin\HostingController@delete')->name('delete');
    });

    Route::prefix('vps')->name('vps.')->group(function() {
        Route::get('/', 'Admin\VPSController@index')->name('index');
        Route::get('/add', 'Admin\VPSController@create')->name('add');
        Route::post('/add', 'Admin\VPSController@store');
        Route::get('/show/{id}', 'Admin\VPSController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\VPSController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\VPSController@update');
        Route::get('/delete/{id}', 'Admin\VPSController@delete')->name('delete');
    });

    Route::prefix('dedicated')->name('dedicated.')->group(function() {
        Route::get('/', 'Admin\ServerController@index')->name('index');
        Route::get('/add', 'Admin\ServerController@create')->name('add');
        Route::post('/add', 'Admin\ServerController@store');
        Route::get('/show/{id}', 'Admin\ServerController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\ServerController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\ServerController@update');
        Route::get('/delete/{id}', 'Admin\ServerController@delete')->name('delete');
    });

    Route::prefix('rack')->name('rack.')->group(function() {
        Route::get('/', 'Admin\RackController@index')->name('index');
        Route::get('/add', 'Admin\RackController@create')->name('add');
        Route::post('/add', 'Admin\RackController@store');
        Route::get('/show/{id}', 'Admin\RackController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\RackController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\RackController@update');
        Route::get('/delete/{id}', 'Admin\RackController@delete')->name('delete');
    });

    Route::prefix('colocation')->name('colocation.')->group(function() {
        Route::get('/', 'Admin\ColocationController@index')->name('index');
        Route::get('/add', 'Admin\ColocationController@create')->name('add');
        Route::post('/add', 'Admin\ColocationController@store');
        Route::get('/show/{id}', 'Admin\ColocationController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\ColocationController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\ColocationController@update');
        Route::get('/delete/{id}', 'Admin\ColocationController@delete')->name('delete');
    });

    Route::prefix('nwall')->name('nwall.')->group(function() {
        Route::get('/', 'Admin\NWallController@index')->name('index');
        Route::get('/add', 'Admin\NWallController@create')->name('add');
        Route::post('/add', 'Admin\NWallController@store');
        Route::get('/show/{id}', 'Admin\NWallController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\NWallController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\NWallController@update');
        Route::get('/delete/{id}', 'Admin\NWallController@delete')->name('delete');
    });

    Route::prefix('seo')->name('seo.')->group(function() {
        Route::get('/', 'Admin\SeoController@index')->name('index');
        Route::get('/add', 'Admin\SeoController@create')->name('add');
        Route::post('/add', 'Admin\SeoController@store');
        Route::get('/show/{id}', 'Admin\SeoController@show');
        Route::get('/edit/{id}', 'Admin\SeoController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\SeoController@update');
        Route::get('/delete/{id}', 'Admin\SeoController@delete')->name('delete');
    });

    Route::prefix('pages')->name('pages.')->group(function() {
        Route::get('/', 'Admin\PageController@index')->name('index');
        Route::get('/add', 'Admin\PageController@create')->name('add');
        Route::post('/add', 'Admin\PageController@store');
        Route::get('/show/{id}', 'Admin\PageController@show');
        Route::get('/edit/{id}', 'Admin\PageController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\PageController@update');
        Route::get('/delete/{id}', 'Admin\PageController@delete')->name('delete');
    });

    Route::prefix('config')->name('config.')->group(function() {
        Route::get('/', 'Admin\ConfigController@index');
        Route::get('/homepage', 'Admin\ConfigController@show_homepage')->name('show_homepage');
        Route::get('/homepage/{id}', 'Admin\ConfigController@edit_homepage')->name('edit_homepage');
        Route::post('/homepage/{id}', 'Admin\ConfigController@update_homepage');
    });
});

nps.vn/routes/web.php
<?php
use App\Http\Controllers\Helper\MAC;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth::routes();

Route::get('/mlogin', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/mlogin', 'Auth\LoginController@login');
// Route::get('/mregister', 'Auth\RegisterController@showRegistrationForm')->name('register');
// Route::post('/mregister/', 'Auth\RegisterController@register');
// Route::get('/mpassword/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
// Route::post('/mpassword/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
// Route::get('/mpassword/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
// Route::post('/mpassword/reset', 'Auth\ResetPasswordController@reset');
Route::get('/logout', 'AuthController@logout')->name('logout');

include base_path('routes/admin.php');
// include base_path('routes/view.php');



Route::get('/', 'Website\HomeController@index')->name('home');
Route::get('su-kien/du-doan-ty-so-viet-nam-malaysia.html', 'Website\HomeController@event');
Route::get('su-kien/du-doan-ket-qua-viet-nam-malaysia.html', 'Website\HomeController@bongda');
Route::get('su-kien/du-doan-ket-qua-viet-nam-indo.html', 'Website\HomeController@vnindo');
// Route::get('/hosting.html', 'Website\HomeController@hosting');
// Route::get('/vps.html', 'Website\HomeController@hosting');
// Route::get('/dedicated.html', 'Website\HomeController@hosting');
// Route::get('/tu-rack.html', 'Website\HomeController@hosting');
Route::get('/2019/04/17/anti-ddos-la-gi', function() {
    return redirect('https://www.nps.vn/kb/blogs/kien-thuc/anti-ddos/dos-ddos-la-gi-cach-chong-hacker-ddos-nhu-the-nao.html');
});

Route::get('/{slug}.html', 'Website\HomeController@page');
// Route::get('/sitemapnps.xml', 'Website\HomeController@xml');
// $segment = '';
// $page = Request::segment(1);
// if (!empty($page)) {
// 	$segment = MAC::redirect_page($page);

// 	if ($segment->status == 200) {
// 		dd($page);
// 		Route::get('/'.$page, 'Website\HomeController@page')->name('page');
// 	}else{
// 		Route::get('/404');
// 	}
// }else{
// 	Route::get('/404');
// }

nps.vn/resources/views/admin/pages/add.blade.php
@extends('admin.home')
@section('content')
<script src="/js/ckeditor.js"></script>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-header">
					<div class="row">
						<div class="col-md-12 card_title">
							<h4>Thêm trang mới</h4>
						</div>
					</div>
				</div>
				@include('admin.notify')
				<div class="card-body">
					<form action="" method="post" accept-charset="utf-8">
						@csrf
						<div class="form-group row">
							<div class="col-md-6 pl-0 form_mac">
								<label class="label_mac">Name</label>
								<input type="text" name="name" class="form-control input_mac" value="{{ old('name') }}" required="" maxlength="200">
							</div>
							<div class="col-md-6 pr-0 form_mac">
								<label class="label_mac">Link</label>
								<input type="text" name="slug" class="form-control input_mac" value="{{ old('link') }}" disabled="">
							</div>
						</div>
						<div class="form-group row">
							<div class="col-md-4 pl-0 form_mac">
								<select name="type" class="form-control select_mac">
									<option value="0" >Type</option>
									@foreach (config('page.type') as $key => $val)
										<option value="{{ $key }}" >{{ $val }}</option>
									@endforeach
								</select>
							</div>
							<div class="col-md-4 form_mac">
								<select name="display" class="form-control select_mac">
									<option value="0" selected>Hide</option>
									<option value="1">Show</option>
								</select>
							</div>
							<div class="col-md-4 pr-0 form_mac">
								<label class="label_mac">Số thứ tự</label>
								<input type="number" step="any" name="stt" class="form-control input_mac" value="{{ old('stt') }}">
							</div>
						</div>
						<div class="form-group text-right">
							<button type="submit" class="btn">Thêm mới</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$(document).ready(function() {
		$('[name="name"]').keyup(function() {
			slug = $('[name="name"]').val();
			slug = replace_vi(slug);
			slug = slug.replace(/\s/gi,'-');
			console.log(slug)
			$('[name="slug"]').val(slug);
		});
	});
</script>
@endsection

nps.vn/resources/views/admin/pages/edit.blade.php
@php
	use App\Http\Controllers\Helper\MAC;
@endphp
@extends('admin.home')
@section('content')
<script src="/ckeditor/ckeditor.js"></script>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-header">
					<div class="row">
						<div class="col-md-12 card_title">
							<h4>Cập nhật trang</h4>
						</div>
					</div>
				</div>
				@include('admin.notify')
				<div class="card-body">
					<form action="" method="post" accept-charset="utf-8">
						@csrf
						<div class="form-group row">
							<div class="col-md-6 pl-0 form_mac">
								<label class="label_mac">Name</label>
								<input type="text" name="name" class="form-control input_mac" value="{{ $data->name }}" required="" maxlength="200">
							</div>
							<div class="col-md-6 pr-0 form_mac">
								<label class="label_mac">Link</label>
								<input type="text" name="slug" class="form-control input_mac" value="{{ $data->slug }}" disabled="">
							</div>
						</div>
						<div class="form-group row">
							<div class="col-md-6 pl-0 form_mac">
								<select name="parent" class="form-control select_mac">
									<option value="0" >No Parent</option>
									@foreach ($list as $item)
										@if ($item->parent_id == 0 && $item->id != $data->id)
										<option value="{{ $item->id }}" {{ @($item->id == $data->parent_id) ? 'selected' : '' }}>{{ $item->name }}</option>
										@endif
									@endforeach
								</select>
							</div>
							<div class="col-md-6 pr-0 form_mac">
								<select name="display" class="form-control select_mac">
									<option value="0" {{ (@$data->display == 0) ? 'selected' : '' }}>Hide</option>
									<option value="1" {{ (@$data->display == 1) ? 'selected' : '' }}>Show</option>
								</select>
							</div>
						</div>
						<div class="form-group row">
							<div class="col-md-6 pl-0 form_mac">
								<select name="type" class="form-control select_mac">
									<option value="0" >--- SELECT TYPE ---</option>
									@foreach (config('page.type') as $key => $val)
										<option value="{{ $key }}" {{ (@$data->type == $key) ? 'selected' : '' }}>{{ $val }}</option>
									@endforeach
								</select>
							</div>
							@if (@$data->type == 'page')
							<div class="col-md-6 pr-0 form_mac">
								<select name="html" class="form-control select_mac">
									<option value="" >--- SELECT HTML ---</option>
									@foreach (config('page.html') as $key => $val)
										<option value="{{ $key }}" {{ (@$data->html == $key) ? 'selected' : '' }}>{{ $val }}</option>
									@endforeach
								</select>
							</div>
							@elseif (@$data->type == 'post')
							<div class="col-md-6 pr-0 form_mac">
								<select name="taxonomy" class="form-control select_mac">
									<option value="0" >--- SELECT CATEGORY ---</option>
									@foreach ($category as $item)
										<option value="{{ $item->id }}" {{ (@$data->taxonomy == $item->id) ? 'selected' : '' }}>{{ $item->name }}</option>
									@endforeach
								</select>
							</div>
							@elseif (@$data->type == 'product')
							<div class="col-md-6 pr-0 form_mac">
								<select name="taxonomy" class="form-control select_mac">
									<option value="0" >--- SELECT CATALOG ---</option>
									@foreach ($catalog as $item)
										<option value="{{ $item->id }}" {{ (@$data->taxonomy == $item->id) ? 'selected' : '' }}>{{ $item->name }}</option>
									@endforeach
								</select>
							</div>
							@endif
						</div>
						<div class="form-group row">
							<div class="col-md-6 pl-0 checkbox_mac">
								@foreach (config('location.taxonomy') as $item)
								<div class="custom-control custom-checkbox d-inline pr-5">
									<input type="checkbox" class="custom-control-input" name="location[]" value="{{ $item }}" id="{{ $item }}_checkbox" {{ (in_array($item, json_decode($data->location))) ? 'checked' : '' }}>
									<label class="custom-control-label" for="{{ $item }}_checkbox">{{ strtoupper($item) }}</label>
								</div>
								@endforeach
							</div>
							<div class="col-md-3 form_mac">
								<label class="label_mac">Độ ưu tiên</label>
								<input type="text" name="priority" class="form-control input_mac" value="{{ $data->priority }}">
							</div>
							<div class="col-md-3 pr-0 form_mac">
								<label class="label_mac">Số thứ tự</label>
								<input type="number" step="any" name="stt" class="form-control input_mac" value="{{ $data->stt }}">
							</div>
						</div>
						<div class="form-group row">
							<div class="col-md-12 px-0 form_mac">
								<label class="label_mac">Tiêu đề trang</label>
								<input type="text" name="page_title" class="form-control input_mac" value="{{ @$data->page_title }}">
							</div>
						</div>
						<div class="form-group row">
							<div class="col-md-12 px-0 form_mac">
								<label class="label_mac">Đường dẫn trang</label>
								<input type="text" name="link" class="form-control input_mac" value="{{ @$data->link }}">
							</div>
						</div>
						<div class="form-group row">
							<div class="col-md-12 px-0">
								<label class="">Nội dung trang</label>
								<textarea id="editor" name="content" class="form-control">{{ @$data->content }}</textarea>
							</div>
						</div>
						<div id="html_seo">
							@if (!empty(json_decode(@$data->meta)))
							@php $str_seo = ''; @endphp
							@foreach (json_decode(@$data->meta) as $key => $val)
								@php $str_seo = $str_seo.','.$key @endphp
								<div class="form-group row">
									<div class="col-md-12 px-0">
										<label class=""><button type="button" class="btn btn-danger btn_del_seo" onclick="return confirm('Bạn có chắn chắn muốn xóa thẻ SEO: {{ $key }} này không?');"><i class="fas fa-minus"></i></button><span class="pl-2">Nội dung thẻ SEO: {{ $key }}</span></label>
										<textarea class="form-control" name="{{ $key }}" rows="5">{!! $val !!}</textarea>
									</div>
								</div>
							@endforeach
							@endif
						</div>
						<div class="form-group row">
							<div class="col-md-2 pl-0">
								<button type="button" class="btn btn-primary" id="btn_add_seo"><i class="fas fa-plus"></i></button>
							</div>
							<div class="col-md-10 pr-0 form_mac">
								<label class="label_mac">Tên thẻ SEO (* phải cùng tên với thẻ SEO muốn thay thế ngoài trang chủ và không nên có ký tự đặc biệt)</label>
								<input type="text" id="name_seo" class="form-control input_mac" value="">
								<input type="text" id="cate_child" name="cate_child" class="form-control input_mac" value="">
								<input type="text" value="{{ @$str_seo }}" name="str_seo" id="str_seo" class="d-none">
							</div>
						</div>
						<div class="form-group text-right">
							<button type="submit" class="btn">Cập nhật</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	@if (!empty($child))
	<div class="row pt-5">
		<div class="col-md-3">
			<div class="card">
				<div class="card-header">
					<div class="row">
						<div class="col-md-12 card_title">
							<h4>Danh sách danh mục con</h4>
						</div>
					</div>
				</div>
				<div class="card-body">
					@foreach ($child as $item)
					<div class="custom-control custom-checkbox pr-5">
						<input type="checkbox" class="custom-control-input child_checkbox" value="{{ $item }}" id="{{ $item }}_checkbox" checked="">
						<label class="custom-control-label" for="{{ $item }}_checkbox">{{ strtoupper(MAC::cateColInList($item, $list, 'name')) }}</label>
					</div>
					@endforeach
				</div>
			</div>
		</div>
	</div>
	@endif
</div>
<style type="text/css" media="screen">
	.btn_del_seo{
		padding: 0 5px;
	}
</style>
<script type="text/javascript">
	$(document).ready(function() {
		$('[name="name"]').keyup(function() {
			slug = $('[name="name"]').val();
			slug = replace_vi(slug);
			slug = slug.replace(/\s/gi,'-');
			$('[name="slug"]').val(slug);
		});
		$('.child_checkbox').change(function() {
			all_checkbox = $('.child_checkbox:checked');
			arr = [];
			all_checkbox.each(function() {
				arr.push($(this).val());
			});
			console.log(arr);
			$('[name="cate_child"]').val(arr);
		});

		$('#btn_add_seo').click(function () {
			name_seo = $('#name_seo').val();
			name_seo = replace_vi(name_seo);
			name_seo = name_seo.replace(/\s/gi,'_');
			str_seo = $('[name="str_seo"]').val();

			if (name_seo == "") {
				alert('Vui lòng điền tên cho thẻ SEO muốn thêm!');
			}else{
				name_seo = 'seo_'+name_seo;
				str_seo = $('[name="str_seo"]').val();
				n = str_seo.indexOf(name_seo);
				if (n == -1) {
					str_seo += ','+name_seo;
					// $('[name="str_seo"]').val(str_seo);
					str_seo = $('[name="str_seo"]').attr('value', str_seo);
					html = `<div class="form-group row">
								<div class="col-md-12 px-0">
									<label class=""><button type="button" class="btn btn-danger btn_del_seo" onclick="return confirm('Bạn có chắn chắn muốn xóa thẻ SEO: `+name_seo+` này không?');"><i class="fas fa-minus"></i></button><span class="pl-2">Nội dung thẻ SEO: `+name_seo+`</span></label>
									<textarea class="form-control" name="`+name_seo+`" rows="5"></textarea>
								</div>
							</div>`;
					$('#html_seo').append(html);
					$('#name_seo').val("");
				}else{
					alert('Thẻ SEO '+name_seo+' đã tồn tại, vui lòng chọn tên khác!');
				}
			}
		});
		del_seo();
		var btnAdd = document.getElementById("btn_add_seo");
		btnAdd.addEventListener("click",function(){
			del_seo();
		});
		function del_seo(){
			var delBtn = Array.from(document.querySelectorAll(".btn_del_seo")),
			strSeoVal = document.getElementById("str_seo");
			delBtn.forEach(function(el){
				el.addEventListener("click",function(){
					var getName = el.parentElement.parentElement.parentElement.firstElementChild.lastElementChild.getAttribute("name");
					el.parentElement.parentElement.parentElement.remove();
					var newValue = strSeoVal.getAttribute("value").replace(getName,"");
					strSeoVal.setAttribute("value",newValue);

				});
			});

		}

	});

	CKEDITOR.replace('editor', {
		height: 700,
        filebrowserBrowseUrl: '{{ asset('ckfinder/ckfinder.html') }}',
        filebrowserImageBrowseUrl: '{{ asset('ckfinder/ckfinder.html?type=Images') }}',
        filebrowserFlashBrowseUrl: '{{ asset('ckfinder/ckfinder.html?type=Flash') }}',
        filebrowserUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files') }}',
        filebrowserImageUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images') }}',
        filebrowserFlashUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash') }}'
    });
</script>
@endsection

nps.vn/resources/views/admin/pages/index.blade.php
@php
	use App\Http\Controllers\Helper\MAC;
@endphp
@extends('admin.home')
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-header">
					<div class="row">
						<div class="col-md-4 card_title">
							<h4>Danh sách các trang</h4>
						</div>
						<div class="col-md-4 text-center btn_add">
							<a href="{{ route('admin.pages.add') }}"><i class="fas fa-plus"></i></a>
						</div>
						<div class="col-md-4 card_search">
							<form action="" method="post" accept-charset="utf-8" class="">
								@csrf
								<div class="input-group justify-content-end">
									<input type="text" class="form-control input_search" name="" value="" placeholder="Search">
									<button type="submit" class="btn btn-white"><i class="fas fa-search"></i></button>
								</div>
							</form>
						</div>
					</div>
				</div>
				@include('admin.notify')
				<div class="card-body">
					<div class="table-responsive">
						<table class="table table-hover table-striped">
							<thead>
								<tr>
									<th>ID</th>
									<th>Name</th>
									<th>Parent</th>
									<th>Type</th>
									<th>Show/ Hide</th>
									<th></th>
								</tr>
							</thead>
							<tbody>
								@foreach (@$list as $item)
								<tr>
									<td>{{ @$item->id }}</td>
									<td><a href="{{ route('admin.pages.edit', ['id' => $item->id]) }}" class="px-0">{{ @$item->name }}</a></td>
									<td>{{ MAC::cateColInList($item->parent_id, $list, 'name') }}</td>
									<td>{{ config('page.type.'.$item->type.'.name') }}</td>
									<td>{{ @($item->display == 1) ? 'Show' : 'Hide' }}</td>
									<td>
										<a href="{{ route('admin.pages.edit', ['id' => $item->id]) }}"><i class="fas fa-edit"></i></a>
										<a href="{{ route('admin.pages.delete', ['id' => $item->id]) }}" onclick="return confirm('Bạn có chắn chắn muốn xóa trang này không?');"><i class="fas fa-trash-alt"></i></a>
									</td>
								</tr>
								@endforeach
							</tbody>
						</table>
						{{ $list->links() }}
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row pt-5">
		<div class="col-md-4">
			<div class="card">
				<div class="card-header">
					<div class="row">
						<div class="col-md-12 card_title">
							<h4>Menu Top</h4>
						</div>
					</div>
				</div>
				<div class="card-body">
					@foreach ($list as $item)
						@if ($item->display == 1 && in_array('menu_top', json_decode($item->location)) && $item->parent_id == 0)
							<div class="category_parent category_show">
								<p>{{ $item->name }}</p>
							</div>
							@if (!empty($item->child))
								@foreach (explode(',', $item->child) as $val)
									<div class="category_child category_show">
										<p>{{ MAC::cateColInList($val, $list, 'name') }}</p>
									</div>
								@endforeach
							@endif
						@endif
					@endforeach
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="card">
				<div class="card-header">
					<div class="row">
						<div class="col-md-12 card_title">
							<h4>Sidebar</h4>
						</div>
					</div>
				</div>
				<div class="card-body">
					@foreach ($list as $item)
						@if ($item->display == 1 && in_array('sidebar', json_decode($item->location)) && $item->parent_id == 0)
							<div class="category_parent category_show">
								<p>{{ $item->name }}</p>
							</div>
							@if (!empty($item->child))
								@foreach (explode(',', $item->child) as $val)
									<div class="category_child category_show">
										<p>{{ MAC::cateColInList($val, $list, 'name') }}</p>
									</div>
								@endforeach
							@endif
						@endif
					@endforeach
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="card">
				<div class="card-header">
					<div class="row">
						<div class="col-md-12 card_title">
							<h4>Footer</h4>
						</div>
					</div>
				</div>
				<div class="card-body">
					@foreach ($list as $item)
						@if ($item->display == 1 && in_array('footer', json_decode($item->location)))
							<div class="category_parent category_show">
								<p>{{ $item->name }}</p>
							</div>
							@if (!empty($item->child))
								@foreach (explode(',', $item->child) as $val)
									<div class="category_child category_show">
										<p>{{ MAC::cateColInList($val, $list, 'name') }}</p>
									</div>
								@endforeach
							@endif
						@endif
					@endforeach
				</div>
			</div>
		</div>
	</div>
</div>
@endsection